# Generated by Django 5.2.6 on 2026-08-03 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('travel_planner', 'Travel Planner'), ('budget', 'Budget'), ('weather', 'Weather'), ('recommendation', 'Recommendation'), ('packing', 'Packing'), ('full_graph', 'Full Planning Graph')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], db_index=True, default='pending', max_length=20)),
                ('input_snapshot', models.JSONField(default=dict, help_text='The exact graph state used as input. Stored for reproducibility and debugging.')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trip', 'agent_type', 'created_at'], name='ai_agents_a_trip_id_002da0_idx')],
            },
        ),
    ]
