# Generated by Django 5.2.6 on 2026-08-01 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_number', models.PositiveSmallIntegerField(help_text='1-indexed day of the trip, kept denormalized alongside `date` for fast display without recomputing from trip.start_date every time.')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_ai_generated', models.BooleanField(default=False, help_text="True for items created by Chapter 12's Travel Planner Agent, False for items a user added or edited manually. Allows the API and UI to distinguish AI-generated activities from user-created activities.")),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerary.itineraryday')),
                ('destination', models.ForeignKey(blank=True, help_text="Optional. SET_NULL, not CASCADE — deactivating/removing a destination must never destroy a user's itinerary item.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='itineraryday',
            constraint=models.UniqueConstraint(fields=('trip', 'day_number'), name='unique_day_number_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='itineraryday',
            constraint=models.UniqueConstraint(fields=('trip', 'date'), name='unique_date_per_trip'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['day', 'order'], name='itinerary_day_order_idx'),
        ),
    ]
