# Generated by Django 5.2.6 on 2026-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='weather_condition',
            field=models.CharField(blank=True, help_text='AI-generated weather summary for this itinerary day.', max_length=100),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='weather_high_f',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected daytime high temperature in Fahrenheit.', null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='weather_low_f',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected nighttime low temperature in Fahrenheit.', null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='weather_precipitation_chance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated chance of precipitation (0-100).', null=True),
        ),
    ]
