services:
  django:
    build:
      context: ../../
      dockerfile: infrastructure/docker/django/Dockerfile

    image: traverse-backend:1.0
    container_name: traverse-backend

    restart: unless-stopped

    env_file:
      - ../env/development.env

    expose:
      - "8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - traverse-network

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: ../../
      dockerfile: infrastructure/docker/django/Dockerfile

    image: traverse-backend:1.0
    container_name: traverse-celery
    hostname: celery

    restart: unless-stopped

    command: >
      celery
      -A config
      worker
      --loglevel=INFO
      --pool=threads

    env_file:
      - ../env/development.env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "celery", "-A", "config", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - traverse-network

  nginx:
    build:
      context: ../docker/nginx
      dockerfile: Dockerfile

    image: traverse-nginx:1.0
    container_name: traverse-nginx

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - django

    networks:
      - traverse-network

  postgres:
    image: postgres:17
    container_name: traverse-postgres

    restart: unless-stopped

    env_file:
      - ../env/development.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - traverse-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8-alpine
    container_name: traverse-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - traverse-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:

networks:
  traverse-network:
    driver: bridge