"""
Database models for the Recommendations application.
"""

from django.db import models

from apps.core.models import (
    TimeStampedModel,
    UUIDPrimaryKeyModel,
)


class RecommendationCategory(models.TextChoices):
    """
    Supported recommendation categories.
    """

    RESTAURANT = "restaurant", "Restaurant"
    ATTRACTION = "attraction", "Attraction"
    HOTEL = "hotel", "Hotel"
    SHOPPING = "shopping", "Shopping"
    EXPERIENCE = "experience", "Experience"
    HIDDEN_GEM = "hidden_gem", "Hidden Gem"


class RecommendationStatus(models.TextChoices):
    """
    Recommendation lifecycle.
    """

    PENDING = "pending", "Pending"
    ACCEPTED = "accepted", "Accepted"
    REJECTED = "rejected", "Rejected"


class Recommendation(
    TimeStampedModel,
    UUIDPrimaryKeyModel,
):
    """
    A destination recommendation generated for a trip.

    Recommendations are intentionally modeled independently from the
    itinerary. They represent candidate destinations that may later
    become accepted by the user and incorporated into travel planning.
    """

    trip = models.ForeignKey(
        "trips.Trip",
        on_delete=models.CASCADE,
        related_name="recommendations",
    )

    destination = models.ForeignKey(
        "destinations.Destination",
        on_delete=models.CASCADE,
        related_name="recommendations",
        help_text=(
            "Every recommendation must reference a destination. "
            "Removing the destination also removes the recommendation."
        ),
    )

    category = models.CharField(
        max_length=20,
        choices=RecommendationCategory.choices,
    )

    score = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        help_text=(
            "Confidence score assigned by the recommendation engine. "
            "Higher values indicate stronger recommendations."
        ),
    )

    reason = models.TextField(
        help_text=(
            "Human-readable explanation describing why this destination "
            "was recommended."
        ),
    )

    status = models.CharField(
        max_length=20,
        choices=RecommendationStatus.choices,
        default=RecommendationStatus.PENDING,
    )

    is_ai_generated = models.BooleanField(
        default=True,
        help_text=(
            "True for recommendations generated by the future AI "
            "Recommendation Engine. False for manually created "
            "recommendations."
        ),
    )

    class Meta:
        verbose_name = "Recommendation"
        verbose_name_plural = "Recommendations"

        ordering = [
            "-score",
        ]

        indexes = [
            models.Index(
                fields=[
                    "trip",
                    "status",
                ],
                name="recommendation_trip_status_idx",
            ),
        ]

    def __str__(self) -> str:
        """
        Return a concise string representation.
        """

        return (
            f"{self.destination.name} "
            f"({self.score})"
        )