"""
Seed placeholder recommendations for a trip.

This command exists exclusively for local development and testing.

Recommendations generated by this command are intentionally fake and are
used until the real AI Recommendation Agent is introduced in Chapter 15.
"""

import random
from decimal import Decimal

from django.core.management.base import (
    BaseCommand,
    CommandError,
)

from apps.destinations.models import Destination
from apps.recommendations.models import (
    Recommendation,
    RecommendationCategory,
)
from apps.trips.models import Trip


MIN_SCORE = 0.50
MAX_SCORE = 0.99


_FAKE_RECOMMENDATIONS = {
    RecommendationCategory.RESTAURANT: [
        "Popular with locals and highly rated for regional cuisine.",
        "Excellent evening dining with panoramic city views.",
        "A great place to sample authentic local street food.",
    ],
    RecommendationCategory.ATTRACTION: [
        "A must-visit destination representing the city's history.",
        "Offers one of the best panoramic views in the region.",
        "Recommended for its cultural and historical significance.",
    ],
    RecommendationCategory.HOTEL: [
        "Comfortable accommodation close to major attractions.",
        "Ideal for travelers seeking premium amenities.",
        "Excellent value for money with convenient access.",
    ],
    RecommendationCategory.SHOPPING: [
        "Known for handcrafted products and local souvenirs.",
        "A large collection of international and local brands.",
        "Ideal for discovering unique locally made products.",
    ],
    RecommendationCategory.EXPERIENCE: [
        "A relaxing experience with spectacular evening scenery.",
        "Explore hidden streets with a knowledgeable local guide.",
        "Learn to prepare authentic regional dishes.",
    ],
    RecommendationCategory.HIDDEN_GEM: [
        "A peaceful location rarely visited by tourists.",
        "A charming local favorite tucked away from busy streets.",
        "One of the city's best overlooked photography locations.",
    ],
}


class Command(BaseCommand):
    """
    Seed placeholder recommendations for a trip.

    This command is intended exclusively for local development and
    testing until the AI Recommendation Engine is implemented.
    """

    help = (
        "Seed fake recommendations for a trip. "
        "Development use only."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "trip_id",
            type=str,
            help="UUID of the trip.",
        )

        parser.add_argument(
            "--count",
            type=int,
            default=5,
            help="Number of recommendations to generate.",
        )

    def handle(self, *args, **options):
        try:
            trip = Trip.objects.get(
                pk=options["trip_id"],
            )

        except Trip.DoesNotExist as exc:
            raise CommandError(
                f"No trip found with id '{options['trip_id']}'."
            ) from exc

        destinations = list(
            trip.destinations.all()
        )

        if not destinations:
            destinations = list(
                Destination.objects.filter(
                    is_active=True,
                )[:5]
            )

        if not destinations:
            raise CommandError(
                "No active destinations are available."
            )

        created = 0

        for _ in range(options["count"]):

            category = random.choice(
                RecommendationCategory.values
            )

            reason = random.choice(
                _FAKE_RECOMMENDATIONS[category]
            )

            Recommendation.objects.create(
                trip=trip,
                destination=random.choice(destinations),
                category=category,
                score=Decimal(
                    f"{random.uniform(MIN_SCORE, MAX_SCORE):.2f}"
                ),
                reason=reason,
            )

            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                (
                    f"Successfully created {created} fake "
                    f"recommendation(s) for trip '{trip.title}'."
                )
            )
        )