# Generated by Django 5.2.6 on 2026-08-02 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('attraction', 'Attraction'), ('hotel', 'Hotel'), ('shopping', 'Shopping'), ('experience', 'Experience'), ('hidden_gem', 'Hidden Gem')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, help_text='Confidence score assigned by the recommendation engine. Higher values indicate stronger recommendations.', max_digits=4)),
                ('reason', models.TextField(help_text='Human-readable explanation describing why this destination was recommended.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=True, help_text='True for recommendations generated by the future AI Recommendation Engine. False for manually created recommendations.')),
                ('destination', models.ForeignKey(help_text='Every recommendation must reference a destination. Removing the destination also removes the recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='destinations.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['trip', 'status'], name='recommendation_trip_status_idx')],
            },
        ),
    ]
