"""
Domain models for the Budget application.
"""

from django.db import models

from apps.core.models import (
    TimeStampedModel,
    UUIDPrimaryKeyModel,
)


class BudgetCategory(models.TextChoices):
    """
    Supported budget categories.
    """

    ACCOMMODATION = (
        "accommodation",
        "Accommodation",
    )

    TRANSPORT = (
        "transport",
        "Transport",
    )

    FOOD = (
        "food",
        "Food & Dining",
    )

    ACTIVITIES = (
        "activities",
        "Activities & Tours",
    )

    SHOPPING = (
        "shopping",
        "Shopping",
    )

    MISC = (
        "misc",
        "Miscellaneous",
    )


class Budget(
    UUIDPrimaryKeyModel,
    TimeStampedModel,
):
    """
    One budget per trip.

    Budgets are automatically created when a Trip is created.
    """

    trip = models.OneToOneField(
        "trips.Trip",
        on_delete=models.CASCADE,
        related_name="budget",
    )

    currency = models.CharField(
        max_length=3,
        default="USD",
    )

    planned_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=(
            "Optional user-defined target budget. "
            "Independent from the computed total of all "
            "budget line items."
        ),
    )

    class Meta:
        verbose_name = "Budget"
        verbose_name_plural = "Budgets"

    def __str__(
        self,
    ) -> str:
        return f"Budget<{self.trip.title}>"


class BudgetLineItem(
    UUIDPrimaryKeyModel,
    TimeStampedModel,
):
    """
    Individual cost entry belonging to a Budget.
    """

    budget = models.ForeignKey(
        Budget,
        on_delete=models.CASCADE,
        related_name="line_items",
    )

    category = models.CharField(
        max_length=20,
        choices=BudgetCategory.choices,
    )

    description = models.CharField(
        max_length=200,
    )

    amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
    )

    is_ai_estimated = models.BooleanField(
        default=False,
        help_text=(
            "True when generated by the future Budget AI "
            "agent. False when entered manually by the user."
        ),
    )

    class Meta:
        ordering = [
            "-created_at",
        ]

        indexes = [
            models.Index(
                fields=[
                    "budget",
                    "category",
                ],
                name="budget_category_idx",
            ),
        ]

        constraints = [
            models.CheckConstraint(
                condition=models.Q(
                    amount__gte=0,
                ),
                name="budget_line_item_amount_gte_0",
            ),
        ]

        verbose_name = "Budget Line Item"

        verbose_name_plural = "Budget Line Items"

    def __str__(
        self,
    ) -> str:
        return (
            f"{self.description}: "
            f"{self.amount} "
            f"({self.category})"
        )