# Generated by Django 5.2.6 on 2026-08-08 14:26

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_packingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(db_index=True, default=apps.documents.models._generate_share_token, help_text='Public capability token. Deliberately distinct from the document primary key.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Owner can revoke a link by deactivating it.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Shared Document Link',
                'verbose_name_plural': 'Shared Document Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
