# Generated by Django 5.2.6 on 2026-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
