# Generated by Django 5.2.6 on 2026-08-05 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('electronics', 'Electronics'), ('documents', 'Documents'), ('medication', 'Medication'), ('accessories', 'Accessories'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=True, help_text='True when this packing item was generated by the AI Packing Agent.')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Packing Item',
                'verbose_name_plural': 'Packing Items',
                'ordering': ['category', 'item'],
                'indexes': [models.Index(fields=['trip', 'category'], name='packing_trip_category_idx')],
            },
        ),
    ]
