# Generated by Django 5.2.6 on 2026-08-02 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('planned_total', models.DecimalField(blank=True, decimal_places=2, help_text='Optional user-defined target budget. Independent from the computed total of all budget line items.', max_digits=10, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('transport', 'Transport'), ('food', 'Food & Dining'), ('activities', 'Activities & Tours'), ('shopping', 'Shopping'), ('misc', 'Miscellaneous')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_ai_estimated', models.BooleanField(default=False, help_text='True when generated by the future Budget AI agent. False when entered manually by the user.')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.budget')),
            ],
            options={
                'verbose_name': 'Budget Line Item',
                'verbose_name_plural': 'Budget Line Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['budget', 'category'], name='budget_category_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='budget_line_item_amount_gte_0')],
            },
        ),
    ]
